name: Stillwaters
favicon: null
layout_spectrum: 0.5276655002962798
typography_spectrum: 0.919620790053159
title: 'Stillwaters Restaurant - Bar, Restaurant, Pizza, Fish Fry - Star Lake, WI'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-36320795-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#596a72'
    - '#2f383d'
    - '#afb4b7'
    - '#d65b2e'
  brandStrength: 0.8342487155459821
  lightness: 0.668251457856968
  saturation: 0.658170884475112
  rhythmicContrast: 0.7608481063507497
purpose: []
