name: Stillwaters
favicon: null
layout_spectrum: 0.5276655002962798
typography_spectrum: 0.919620790053159
title: 'Stillwaters Restaurant - Bar, Restaurant, Pizza, Fish Fry - Star Lake, WI'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8342487155459821
  lightness: 0.668251457856968
  saturation: 0.658170884475112
  rhythmicContrast: 0.7608481063507497
purpose: []
